module.exports = {
  LAYERS_MAX_REPORT: 100,
  LAYERS_MAX_COUNT: 1000,

  ATTRIBUTES_MAX_REPORT: 100,
  ATTRIBUTES_MAX_COUNT: 1000,

  VALUES_MAX_REPORT: 100,
  VALUES_MAX_COUNT: 1000,

  VALUE_STRING_MAX_LENGTH: 256,

  EXTNAME_GEOJSON: '.geojson',
  EXTNAME_SHAPEFILE: '.shp',
  EXTNAME_MBTILES: '.mbtiles',

  VALUE_TYPE_STRING: 'String',
  VALUE_TYPE_NUMBER: 'Number',
  VALUE_TYPE_BOOLEAN: 'Boolean',
  VALUE_TYPE_NULL: 'Null',
  VALUE_TYPE_MIXED: 'Mixed',
};
