'use strict';

module.exports = {
  LAYERS_MAX_REPORT: 100,
  LAYERS_MAX_COUNT: 1000,

  ATTRIBUTES_MAX_REPORT: 100,
  ATTRIBUTES_MAX_COUNT: 1000,

  VALUES_MAX_REPORT: 10000,
  VALUES_MAX_COUNT: 100000,

  VALUE_STRING_MAX_LENGTH: 256,
  NAME_TRUNCATE_LENGTH: 256,

  MBTILES_MAX_TILE_COUNT: 1000,

  FILETYPE_GEOJSON: 'geojson',
  FILETYPE_SHAPEFILE: 'shp',
  FILETYPE_CSV: 'csv',
  FILETYPE_MBTILES: 'mbtiles',

  VALUE_TYPE_STRING: 'string',
  VALUE_TYPE_NUMBER: 'number',
  VALUE_TYPE_BOOLEAN: 'boolean',
  VALUE_TYPE_NULL: 'null',
  VALUE_TYPE_MIXED: 'mixed',
};
